spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml

  datasource:
    url: ${DATASOURCE_URL:}
    username: ${DATASOURCE_USERNAME:}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:  ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
    template:
      name: mail-template.html

  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org:
      springframework:
        web: DEBUG
    hibernate:
      SQL: DEBUG

application:
  name: event-management-system

secret: abcdefghijklmnopqrstuvwxyz1234567890abcdefdfdsgshhshfdgsdfsrsdfsdgdfhfjjffdgdfhfdhdhfhdfhdf
expirationMs: 3600000 # 1 hour
refreshExpirationMs: 86400000 # 24 hours


access_token:
  secret_key: FHghAas4HaafJA5ghk3HAF
  lifetime: 3600000
refresh_token:
  secret_key: ZFDF8GJS4ADFA64ASDeimY
  lifetime: 3000000

jwtSecret: ZFDF8GJS4ADFA64ASDeimY
